### ISSUE TITLE
PROBLEMA AL INSTALAR EL MODULO

### ISSUE THREAD

**Issue by CarlosROFA** [OCA/account-invoice-reporting#128]
Error:
Odoo Server Error

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 1101, in _validate_fields
    check(self)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_ui_view.py", line 345, in _check_xml
    view_def = view.read_combined(['arch'])
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_ui_view.py", line 780, in read_combined
    arch = self.apply_view_inheritance(arch_tree, root.id, self.model)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_ui_view.py", line 729, in apply_view_inheritance
    source = self.apply_inheritance_specs(source, specs_tree, view_id)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_ui_view.py", line 707, in apply_inheritance_specs
    self.raise_view_error(_("Element '%s' cannot be located in parent view") % tag, inherit_id)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_ui_view.py", line 545, in raise_view_error
    raise ValueError(message)
ValueError: El elemento '<xpath expr="//t[@t-foreach='o.lines_grouped_by_picking()']//td[hasclass('o_price_total')]">' no puede ser localizado en la vista padre

Contexto del error:
Vista `report_invoice_document`
[view_id: 2215, xml_id: n/a, model: n/a, parent_id: 562]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 757, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 735, in _tag_template
    return self._tag_record(record, data_node)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 662, in _tag_record
    record = model.with_context(rec_context)._load_records([data], self.mode == 'update')
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 3804, in _load_records
    records = self.create([data['values'] for data in to_create])
  File "<decorator-gen-32>", line 2, in create
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 452, in _model_create_multi
    return create(self, arg)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_ui_view.py", line 425, in create
    return super(View, self).create(vals_list)
  File "<decorator-gen-3>", line 2, in create
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 452, in _model_create_multi
    return create(self, arg)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 3541, in create
    fields[0].determine_inverse(batch_recs)
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 1104, in determine_inverse
    getattr(records, self.inverse)()
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_ui_view.py", line 275, in _inverse_arch
    view.write(data)
  File "/usr/lib/python3/dist-packages/odoo/addons/website/models/ir_ui_view.py", line 41, in write
    return super(View, self).write(vals)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_ui_view.py", line 441, in write
    return super(View, self).write(self._compute_defaults(vals))
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 3258, in write
    self._write(store_vals)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 3402, in _write
    self._validate_fields(vals)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 1105, in _validate_fields
    raise ValidationError("%s\n\n%s" % (_("Error while validating constraint"), tools.ustr(e)))
odoo.exceptions.ValidationError: ('Error mientras se validaban las restricciones\n\nEl elemento \'<xpath expr="//t[@t-foreach=\'o.lines_grouped_by_picking()\']//td[hasclass(\'o_price_total\')]">\' no puede ser localizado en la vista padre\n\nContexto del error:\nVista `report_invoice_document`\n[view_id: 2215, xml_id: n/a, model: n/a, parent_id: 562]', None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 654, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 312, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 696, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 344, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 337, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 939, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 517, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 966, in call_button
    action = self._call_kw(model, method, args, {})
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 954, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 749, in call_kw
    return _call_kw_multi(method, model, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 736, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-61>", line 2, in button_immediate_install
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_module.py", line 71, in check_and_log
    return method(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_module.py", line 442, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_module.py", line 535, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/usr/lib/python3/dist-packages/odoo/modules/registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 421, in load_modules
    loaded_modules, update_module, models_to_check)
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 313, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 222, in load_module_graph
    load_data(cr, idref, mode, kind='data', package=package, report=report)
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 68, in load_data
    tools.convert_file(cr, package.name, filename, idref, mode, noupdate, kind, report)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 801, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 864, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 763, in parse
    exc_info[2]
  File "/usr/lib/python3/dist-packages/odoo/tools/pycompat.py", line 86, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 757, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 735, in _tag_template
    return self._tag_record(record, data_node)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 662, in _tag_record
    record = model.with_context(rec_context)._load_records([data], self.mode == 'update')
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 3804, in _load_records
    records = self.create([data['values'] for data in to_create])
  File "<decorator-gen-32>", line 2, in create
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 452, in _model_create_multi
    return create(self, arg)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_ui_view.py", line 425, in create
    return super(View, self).create(vals_list)
  File "<decorator-gen-3>", line 2, in create
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 452, in _model_create_multi
    return create(self, arg)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 3541, in create
    fields[0].determine_inverse(batch_recs)
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 1104, in determine_inverse
    getattr(records, self.inverse)()
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_ui_view.py", line 275, in _inverse_arch
    view.write(data)
  File "/usr/lib/python3/dist-packages/odoo/addons/website/models/ir_ui_view.py", line 41, in write
    return super(View, self).write(vals)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_ui_view.py", line 441, in write
    return super(View, self).write(self._compute_defaults(vals))
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 3258, in write
    self._write(store_vals)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 3402, in _write
    self._validate_fields(vals)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 1105, in _validate_fields
    raise ValidationError("%s\n\n%s" % (_("Error while validating constraint"), tools.ustr(e)))
odoo.tools.convert.ParseError: "Error mientras se validaban las restricciones

El elemento '<xpath expr="//t[@t-foreach='o.lines_grouped_by_picking()']//td[hasclass('o_price_total')]">' no puede ser localizado en la vista padre

Contexto del error:
Vista `report_invoice_document`
[view_id: 2215, xml_id: n/a, model: n/a, parent_id: 562]
None" while parsing None:4, near
<data inherit_id="account.report_invoice_document" priority="99">
    <xpath expr="//t[contains(@t-foreach, 'o.invoice_line_ids')]/t[3]" position="replace">

    </xpath>
    <xpath expr="//tbody[hasclass('invoice_tbody')]" position="inside">
        <t t-set="subtotal" t-value="0.0"/>
        <t t-set="lines_grouped" t-value="o.lines_grouped_by_picking()"/>
    </xpath>

    <xpath expr="//t[contains(@t-foreach, 'o.invoice_line_ids')]" position="attributes">
        <attribute name="t-foreach">o.lines_grouped_by_picking()</attribute>
        <attribute name="t-as">lines_group</attribute>
    </xpath>

    
    <xpath expr="//t[@groups='account.group_show_line_subtotals_tax_excluded']" position="before">
        <t t-set="l" t-value="lines_group['line']"/>
        <t t-set="line" t-value="lines_group['line']"/>
        <t t-set="picking" t-value="lines_group['picking']"/>
        <t t-set="lines_grouped" t-value="o.lines_grouped_by_picking()"/>
        <t t-set="next_picking" t-value="[lines_grouped[i + 1]['picking'] for i, x in enumerate(lines_grouped) if x == lines_group and i &lt; len(lines_grouped) - 1] or [False]"/>
        <t t-if="picking != last_picking">
            <tr t-if="picking">
                <td colspan="10">
                    <strong>
                        <span>Order:</span>
                        <span t-field="picking.sale_id.name"/>
                        <t t-if="picking.sale_id.client_order_ref">
                            <span t-translation="off"> (</span><span t-field="picking.sale_id.client_order_ref"/><span t-translation="off">)</span>
                        </t>
                        <span>Picking:</span>
                        <span t-field="picking.date_done" t-options="{'widget': 'date'}"/>
                        <span t-field="picking.name"/>
                    </strong>
                </td>
            </tr>
        </t>
    </xpath>

    <xpath expr="//td/span[@t-field='line.quantity']" position="attributes">
        <attribute name="t-esc">lines_group['quantity']</attribute>
        <attribute name="t-field"/>
        <attribute name="t-options">{'widget': 'float', 'decimal_precision': 'Product Unit of Measure'}</attribute>
    </xpath>

    <xpath expr="//td/span[@t-field='line.price_subtotal']" position="before">
        <t t-if="lines_group['quantity'] != l.quantity" id="picking_subtotal" groups="!account.group_show_line_subtotals_tax_included">
            
            <t t-set="line_picking_subtotal" t-value="l.quantity and lines_group['quantity'] * (l.price_subtotal / l.quantity) or 0.0"/>
            <t t-set="subtotal" t-value="(subtotal or 0.0) + line_picking_subtotal"/>
            <span t-esc="line_picking_subtotal" t-options="{&quot;widget&quot;: &quot;monetary&quot;, &quot;display_currency&quot;: o.currency_id}"/>
        </t>
        <t t-else="">
            <t t-set="subtotal" t-value="(subtotal or 0.0) + l.price_subtotal"/>
        </t>
    </xpath>

    <xpath expr="//td/span[@t-field='line.price_subtotal']" position="attributes">
        <attribute name="t-if">lines_group['quantity'] == l.quantity</attribute>
    </xpath>

    <xpath expr="//td/span[@t-field='line.price_total']" position="attributes">
        <attribute name="t-if">lines_group['quantity'] == l.quantity</attribute>
    </xpath>

    
    <xpath expr="//t[@t-foreach='o.lines_grouped_by_picking()']//td[hasclass('o_price_total')]" position="after">
        <tr t-if="picking and picking != next_picking[0]">
            <td colspan="10" class="text-right">
                <strong>Subtotal: </strong>
                <strong t-esc="subtotal" t-options="{&quot;widget&quot;: &quot;monetary&quot;, &quot;display_currency&quot;: o.currency_id}"/>
            </td>
            <t t-set="subtotal" t-value="0.0"/>
        </tr>
        <t t-set="last_picking" t-value="picking"/>
    </xpath>

    
    <xpath expr="//td/span[@t-field='line.price_total']" position="before">
        <t t-if="lines_group['quantity'] != l.quantity" groups="account.group_show_line_subtotals_tax_included">
            
            <t t-set="line_picking_subtotal" t-value="l.quantity and lines_group['quantity'] * (l.price_total / l.quantity) or 0.0"/>
            <t t-set="subtotal" t-value="(subtotal or 0.0) + line_picking_subtotal"/>
            <span t-esc="line_picking_subtotal" t-options="{&quot;widget&quot;: &quot;monetary&quot;, &quot;display_currency&quot;: o.currency_id}"/>
        </t>
        <t t-else="">
            <t t-set="subtotal" t-value="(subtotal or 0.0) + l.price_total"/>
        </t>
    </xpath>

    <xpath expr="//td/span[@t-field='line.price_total']" position="attributes">
        <attribute name="t-if">lines_group['quantity'] == l.quantity</attribute>
    </xpath>
</data>

**Comment by pedrobaeza** [comment]
Write in English in this repo.

The error is due to other modules or modifications you have that altered the report views.

**Comment by CarlosROFA** [comment]
It is a new installation V12. There are only 2 modules installed and the complementary ones. All originals of ODOO SA
 Inventory (stock)
 Invoicing (account)

Thanks

**Comment by pedrobaeza** [comment]
You can try in https://runbot.odoo-community.org/runbot/94/12.0 that there's no such problem.

**Comment by CarlosROFA** [comment]
I tryed in https://runbot.odoo-community.org/runbot/94/12.0 but in this page has another misteck.

Error:
Odoo Server Error

Traceback (most recent call last):
  File "/home/odoo/OCB-12.0/addons/web/controllers/main.py", line 1671, in report_download
    response = self.report_routes(reportname, docids=docids, converter=converter)
  File "/.repo_requirements/odoo/odoo/http.py", line 519, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo/OCB-12.0/addons/web/controllers/main.py", line 1612, in report_routes
    pdf = report.with_context(context).render_qweb_pdf(docids, data=data)[0]
  File "/.repo_requirements/odoo/odoo/addons/base/models/ir_actions_report.py", line 733, in render_qweb_pdf
    return self._post_pdf(save_in_attachment, pdf_content=pdf_content, res_ids=html_ids), 'pdf'
  File "/home/odoo/OCB-12.0/addons/account_facturx/models/ir_actions_report.py", line 25, in _post_pdf
    writer.cloneReaderDocumentRoot(reader)
AttributeError: 'PdfFileWriter' object has no attribute 'cloneReaderDocumentRoot'


Thanks

**Comment by pedrobaeza** [comment]
That's because an error in other module. Uninstall account_facturx.
