### ISSUE TITLE
The database does not start

### ISSUE THREAD

**Issue by SGiuseppe** [OCA/account-invoice-reporting#39]
module: account_invoice_production_lot
version: 8.0

**Steps to reproduce**
module installation creates problems on the database. To make it work I had to install the module commenting code _init_.py in this way:
       from . import invoice
       #from . import tests

**Comment by eLBati** [comment]
@SGiuseppe thanks.
@archetipo can you check?

**Comment by SGiuseppe** [comment]
Steps to show the error:
1. backup of a database without the module in question
2. database restore with a different name
3. log in to the database you just created and install the module
4. logout from the database. at this point we are in the Choose Database
5. stop the server and shut down the computer for a few minutes
6. turn on the PC and restart the server odoo-8
7. at this point in the screen of the choice of the database to connect to it.

now you should give the error. as shown in my case below:

```
odoo@opensuse-virtuale:/home/giuseppe> /home/odoo/8.0-git/odoo/openerp-server -c /etc/odoo/openerp-server-git.conf 
2015-09-13 11:12:41,557 2528 INFO ? openerp: OpenERP version 8.0
2015-09-13 11:12:41,558 2528 INFO ? openerp: addons paths: ['/home/odoo/.local/share/Odoo/addons/8.0', u'/home/odoo/8.0-git/odoo/addons', u'/home/odoo/8.0-git/odoo/addons-extra', '/home/odoo/8.0-git/odoo/openerp/addons']
2015-09-13 11:12:41,558 2528 INFO ? openerp: database hostname: localhost
2015-09-13 11:12:41,558 2528 INFO ? openerp: database port: 5432
2015-09-13 11:12:41,559 2528 INFO ? openerp: database user: odoo
2015-09-13 11:12:45,453 2528 INFO ? openerp.service.server: HTTP service (werkzeug) running on 0.0.0.0:8069
2015-09-13 11:13:50,008 2528 INFO ? openerp.addons.bus.bus: Bus.loop listen imbus on db postgres
2015-09-13 11:14:04,372 2528 INFO ? openerp.addons.report.models.report: Will use the Wkhtmltopdf binary at /usr/bin/wkhtmltopdf
2015-09-13 11:14:10,051 2528 WARNING ? openerp.addons.base_contact.deprecated: This module is DEPRECATED. See /home/odoo/8.0-git/odoo/addons-extra/base_contact/README.rst.
2015-09-13 11:14:13,084 2528 INFO ? openerp.http: HTTP Configuring static files
2015-09-13 11:14:14,695 2528 INFO pippo1 openerp.modules.loading: loading 1 modules...
2015-09-13 11:14:14,710 2528 INFO pippo1 openerp.modules.loading: 1 modules loaded in 0.01s, 0 queries
2015-09-13 11:14:15,388 2528 INFO pippo1 openerp.modules.loading: loading 52 modules...
2015-09-13 11:14:17,880 2528 INFO pippo1 openerp.modules.loading: 52 modules loaded in 2.49s, 0 queries
2015-09-13 11:14:19,481 2528 INFO pippo1 openerp.modules.loading: Modules loaded.
2015-09-13 11:14:19,483 2528 INFO pippo1 openerp.addons.base.ir.ir_http: Generating routing map
2015-09-13 11:14:24,580 2528 INFO pippo1 werkzeug: 192.168.1.30 - - [13/Sep/2015 11:14:24] "POST /web/login HTTP/1.1" 303 -
2015-09-13 11:14:26,490 2528 ERROR pippo1 openerp.sql_db: bad query: SELECT value
                       FROM ir_translation
                       WHERE lang='it_IT'
                        AND type in ('code', 'sql_constraint')
                        AND src='document'
Traceback (most recent call last):
  File "/home/odoo/8.0-git/odoo/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
InternalError: ERRORE:  l'indice "ir_translation_src_hash_idx" contiene una pagina inaspettata completamente a zero al blocco 0
NOTA: Si richiede l'esecuzione di REINDEX.

2015-09-13 11:14:26,538 2528 ERROR pippo1 openerp.sql_db: bad query: SELECT "ir_config_parameter".id FROM "ir_config_parameter" WHERE ("ir_config_parameter"."key" = 'mail.catchall.domain') ORDER BY "ir_config_parameter"."id"  
Traceback (most recent call last):
  File "/home/odoo/8.0-git/odoo/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
InternalError: ERRORE:  la transazione corrente è interrotta, i comandi saranno ignorati fino alla fine del blocco della transazione

2015-09-13 11:14:26,841 2528 INFO pippo1 werkzeug: 192.168.1.30 - - [13/Sep/2015 11:14:26] "GET /web HTTP/1.1" 500 -
2015-09-13 11:14:27,458 2528 ERROR pippo1 werkzeug: Error on request:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/werkzeug/serving.py", line 177, in run_wsgi
    execute(self.server.app)
  File "/usr/lib/python2.7/site-packages/werkzeug/serving.py", line 165, in execute
    application_iter = app(environ, start_response)
  File "/home/odoo/8.0-git/odoo/openerp/service/server.py", line 290, in app
    return self.app(e, s)
  File "/home/odoo/8.0-git/odoo/openerp/service/wsgi_server.py", line 216, in application
    return application_unproxied(environ, start_response)
  File "/home/odoo/8.0-git/odoo/openerp/service/wsgi_server.py", line 202, in application_unproxied
    result = handler(environ, start_response)
  File "/home/odoo/8.0-git/odoo/openerp/http.py", line 1290, in __call__
    return self.dispatch(environ, start_response)
  File "/home/odoo/8.0-git/odoo/openerp/http.py", line 1264, in __call__
    return self.app(environ, start_wrapped)
  File "/usr/lib/python2.7/site-packages/werkzeug/wsgi.py", line 588, in __call__
    return self.app(environ, start_response)
  File "/home/odoo/8.0-git/odoo/openerp/http.py", line 1435, in dispatch
    result = ir_http._dispatch()
  File "/home/odoo/8.0-git/odoo/openerp/addons/base/ir/ir_http.py", line 175, in _dispatch
    return self._handle_exception(e)
  File "/home/odoo/8.0-git/odoo/openerp/addons/base/ir/ir_http.py", line 145, in _handle_exception
    return request._handle_exception(exception)
  File "/home/odoo/8.0-git/odoo/openerp/http.py", line 666, in _handle_exception
    return super(HttpRequest, self)._handle_exception(exception)
  File "/home/odoo/8.0-git/odoo/openerp/addons/base/ir/ir_http.py", line 171, in _dispatch
    result = request.dispatch()
  File "/home/odoo/8.0-git/odoo/openerp/http.py", line 684, in dispatch
    r = self._call_function(**self.params)
  File "/home/odoo/8.0-git/odoo/openerp/http.py", line 310, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/odoo/8.0-git/odoo/openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/odoo/8.0-git/odoo/openerp/http.py", line 307, in checked_call
    return self.endpoint(*a, **kw)
  File "/home/odoo/8.0-git/odoo/openerp/http.py", line 803, in __call__
    return self.method(*args, **kw)
  File "/home/odoo/8.0-git/odoo/openerp/http.py", line 403, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo/8.0-git/odoo/addons/web/controllers/main.py", line 477, in web_client
    menu_data = request.registry['ir.ui.menu'].load_menus(request.cr, request.uid, context=request.context)
  File "/home/odoo/8.0-git/odoo/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "<string>", line 2, in load_menus

  File "/home/odoo/8.0-git/odoo/openerp/tools/cache.py", line 122, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/home/odoo/8.0-git/odoo/openerp/addons/base/ir/ir_ui_menu.py", line 381, in load_menus
    menu_root_ids = self.get_user_roots(cr, uid, context=context)
  File "/home/odoo/8.0-git/odoo/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/odoo/8.0-git/odoo/openerp/addons/base/ir/ir_ui_menu.py", line 355, in get_user_roots
    return self.search(cr, uid, menu_domain, context=context)
  File "/home/odoo/8.0-git/odoo/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/odoo/8.0-git/odoo/addons/mail/mail_group_menu.py", line 42, in search
    context=context, count=False)
  File "/home/odoo/8.0-git/odoo/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/odoo/8.0-git/odoo/openerp/addons/base/ir/ir_ui_menu.py", line 128, in search
    result = self._filter_visible_menus(cr, uid, ids, context=context)
  File "/home/odoo/8.0-git/odoo/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/odoo/8.0-git/odoo/openerp/api.py", line 363, in old_api
    result = method(recs, *args, **kwargs)
  File "/home/odoo/8.0-git/odoo/openerp/addons/base/ir/ir_ui_menu.py", line 99, in _filter_visible_menus
    if not fname or not menu.action[fname] or \
  File "/home/odoo/8.0-git/odoo/openerp/models.py", line 5587, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/home/odoo/8.0-git/odoo/openerp/fields.py", line 817, in __get__
    self.determine_value(record)
  File "/home/odoo/8.0-git/odoo/openerp/fields.py", line 910, in determine_value
    record._prefetch_field(self)
  File "/home/odoo/8.0-git/odoo/openerp/api.py", line 239, in wrapper
    return new_api(self, *args, **kwargs)
  File "/home/odoo/8.0-git/odoo/openerp/models.py", line 3232, in _prefetch_field
    result = records.read(list(fnames), load='_classic_write')
  File "/home/odoo/8.0-git/odoo/openerp/api.py", line 239, in wrapper
    return new_api(self, *args, **kwargs)
  File "/home/odoo/8.0-git/odoo/openerp/api.py", line 547, in new_api
    result = method(self._model, cr, uid, self.ids, *args, **kwargs)
  File "/home/odoo/8.0-git/odoo/openerp/addons/base/ir/ir_actions.py", line 332, in read
    res['help'] = self.pool[model].get_empty_list_help(cr, uid, res.get('help', ""), context=ctx)
  File "/home/odoo/8.0-git/odoo/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/odoo/8.0-git/odoo/addons/mail/mail_thread.py", line 114, in get_empty_list_help
    catchall_domain = ir_config_parameter.get_param(cr, SUPERUSER_ID, "mail.catchall.domain", context=context)
  File "/home/odoo/8.0-git/odoo/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/odoo/8.0-git/odoo/openerp/addons/base/ir/ir_config_parameter.py", line 79, in get_param
    ids = self.search(cr, uid, [('key','=',key)], context=context)
  File "/home/odoo/8.0-git/odoo/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/odoo/8.0-git/odoo/openerp/models.py", line 1644, in search
    return self._search(cr, user, args, offset=offset, limit=limit, order=order, context=context, count=count)
  File "/home/odoo/8.0-git/odoo/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/odoo/8.0-git/odoo/openerp/models.py", line 4672, in _search
    cr.execute(query_str, where_clause_params)
  File "/home/odoo/8.0-git/odoo/openerp/sql_db.py", line 158, in wrapper
    return f(self, *args, **kwargs)
  File "/home/odoo/8.0-git/odoo/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
InternalError: ERRORE:  la transazione corrente è interrotta, i comandi saranno ignorati fino alla fine del blocco della transazione
```
